### PR TITLE
add chinese translation

### PR DESCRIPTION
**Pull request by asqwedcxz741**
add chinese translation.

### CODE REVIEW

**Comment by asqwedcxz741** [comment]
Hello, your mod has improved my game experience, thank you! This is the Chinese translation for [WhatAreYouMissing]. In addition, I want to tell you a question. In the "money collection package" of the community center collection package, "money" will be displayed as "error item", and this object has no icon.
My English communication level is not good. These words are translated by machine. I hope you can understand them. Thank you again!

**Comment by asqwedcxz741** [comment]
Oh, there is another question. In your default.json, is the description of "glacierfish" and "legend" repeated?

In addition, I am also using "SVE" mod. Have you considered increasing the compatibility support for "SVE" specific areas? Like "blue moon vineyard"?

Thank you again for your hard work!

**Comment by LukeSeewald** [comment]
I'm glad to hear you've enjoyed using the mod! Thank you for doing the translating, I'll credit you as asqwedcxz741 on the nexus page unless you prefer a different name. I haven't seen an issue with the money bundle but maybe that's because I haven't looked hard enough. I'll take another look. 

The description of "glacierfish" and "legend" are not repeated, they are different. 

To my knowledge, it should be compatible with SVE fish like those from "blue moon vineyard", at least it was when I had last checked. Are you on the most updated version of the mod?

Thanks again!

**Comment by LukeSeewald** [comment]
You're right about the money, I'll see what I can do

**Pull request merged**
